export const PlaybackActionTypes = {
  SET_CURRENT_PLAYING_TRACK: 'SET_CURRENT_PLAYING_TRACK',
  SET_CURRENT_PLAYBACK_STATE: 'SET_CURRENT_PLAYBACK_STATE',
  SET_PLAYING: 'SET_PLAYING',
  SET_SHUFFLE_STATE: 'SET_SHUFFLE_STATE',
  SET_REPEAT_STATE: 'SET_REPEAT_STATE',
  SET_VOLUME_STATE: 'SET_VOLUME_STATE',
}
